/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dc9c9463-28c0-40c4-b369-077f952f7a9a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0XbXfo8eV",
    "aws_user_pools_web_client_id": "2j4q0nit0gjr5olqunjgu431u5",
    "oauth": {}
};


export default awsmobile;
